openbank.datasource:
  url: jdbc:postgresql://openbankdb:5432/openbank
  username: openbank_user
  password: ENC(BRvskNui+dI2tl1w23UMPFTI8aVXV/iC/KCXqqWqxPpCJYrkNtqi5QBXbkZ+JWvQTxV0RG38nWs9ByPd6Am9AQ==)
  driverclassname: org.postgresql.Driver

security.datasource:
  url: jdbc:postgresql://securitydb:5432/security
  username: security_user
  password: ENC(FStSVsadRTmYp7SXKvqMdjRZnw+lHM/TbQlg7Gaz9kxTBtZEtMGBpyV7btZp19Ofw6gr6FNPrzjIHiZZUf9W1g==)
  driverclassname: org.postgresql.Driver

server.port: 8443
server.ssl.key-store-type: PKCS12
server.ssl.key-store: classpath:ssl/keystore/jsquad.pfx
server.ssl.key-store-password: ENC(K5kJ3wPuXD5f3/GXRczng3nNzkIxKpFGPOtreNZUhVgjNrakjF8ZPJH3oGI3boWh)
server.ssl.enabled: true

world.webclient.baseUrl: http://mockserver:1080

management.endpoint:
  prometheus:
    enabled: true
  metrics.enabled: true

management:
  server:
    port: 8081
    ssl:
      enabled: false

management.endpoints:
  web:
    base-path: /actuator
    exposure.include: 'shallowhealth,deephealth,metrics,prometheus'

management.metrics.export.prometheus.enabled: true

service:
  basic:
    auth:
      map:
        client1:
          token: ENC(ELVLI8foga4ozzKyCp3Lc0N5Q3jE1cflhqTop5NiFtZbvdD0clRgxCrisYPAY+HPWFPA4i9vn/ga9dygfuaisw==)