#
# Copyright 2021 JSquad AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "2.4"
services:
  mockserver:
    image: jamesdbloom/mockserver:mockserver-5.11.2
    expose:
      - "1080"
    ports:
      - 1080:1080
  openbankdb:
    image: postgres:9.6.20
    environment:
      POSTGRES_DB: 'openbank'
      POSTGRES_USER: openbank_user
      POSTGRES_PASSWORD: ${OPENBANK_PASSWORD}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'echo ready || exit 1'"]
      interval: 10s
      timeout: 10s
      retries: 5
  securitydb:
    image: postgres:9.6.20
    environment:
      POSTGRES_DB: 'security'
      POSTGRES_USER: security_user
      POSTGRES_PASSWORD: ${SECURITY_PASSWORD}
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'echo ready || exit 1'"]
      interval: 10s
      timeout: 10s
      retries: 5
  flyway:
    image: flyway/flyway:6.0.6
    command: -url=jdbc:postgresql://securitydb:5432/security -schemas=public -user=security_user -password=${SECURITY_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ../security/sql:/flyway/sql
    depends_on:
      securitydb:
        condition: service_healthy
  openbank:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MASTER_SECRET: "${MASTER_KEY}"
      CONFIG_FILE_LOCATIONS: "classpath:application.properties,classpath:configuration_local.yaml,classpath:activemq.properties,classpath:openbank_jpa.yaml,classpath:security_jpa.yaml"
    expose:
      - "8443"
      - "8081"
    ports:
      - 8443:8443
      - 8081:8081
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo ready || exit 1'"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      openbankdb:
        condition: service_healthy
      securitydb:
        condition: service_healthy